// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/LGUG2Z/call-me/models"
)

// GetMaybeHandlerFunc turns a function with the right signature into a get maybe handler
type GetMaybeHandlerFunc func(GetMaybeParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMaybeHandlerFunc) Handle(params GetMaybeParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetMaybeHandler interface for that can handle valid get maybe params
type GetMaybeHandler interface {
	Handle(GetMaybeParams, *models.Principal) middleware.Responder
}

// NewGetMaybe creates a new http.Handler for the get maybe operation
func NewGetMaybe(ctx *middleware.Context, handler GetMaybeHandler) *GetMaybe {
	return &GetMaybe{Context: ctx, Handler: handler}
}

/*GetMaybe swagger:route GET /maybe getMaybe

Check if there is an open slot

*/
type GetMaybe struct {
	Context *middleware.Context
	Handler GetMaybeHandler
}

func (o *GetMaybe) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMaybeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
