// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetMaybeOKCode is the HTTP code returned for type GetMaybeOK
const GetMaybeOKCode int = 200

/*GetMaybeOK OK

swagger:response getMaybeOK
*/
type GetMaybeOK struct {
}

// NewGetMaybeOK creates GetMaybeOK with default headers values
func NewGetMaybeOK() *GetMaybeOK {

	return &GetMaybeOK{}
}

// WriteResponse to the client
func (o *GetMaybeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetMaybeForbiddenCode is the HTTP code returned for type GetMaybeForbidden
const GetMaybeForbiddenCode int = 403

/*GetMaybeForbidden Forbidden

swagger:response getMaybeForbidden
*/
type GetMaybeForbidden struct {
}

// NewGetMaybeForbidden creates GetMaybeForbidden with default headers values
func NewGetMaybeForbidden() *GetMaybeForbidden {

	return &GetMaybeForbidden{}
}

// WriteResponse to the client
func (o *GetMaybeForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetMaybeInternalServerErrorCode is the HTTP code returned for type GetMaybeInternalServerError
const GetMaybeInternalServerErrorCode int = 500

/*GetMaybeInternalServerError Internal Server Error

swagger:response getMaybeInternalServerError
*/
type GetMaybeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetMaybeInternalServerError creates GetMaybeInternalServerError with default headers values
func NewGetMaybeInternalServerError() *GetMaybeInternalServerError {

	return &GetMaybeInternalServerError{}
}

// WithPayload adds the payload to the get maybe internal server error response
func (o *GetMaybeInternalServerError) WithPayload(payload string) *GetMaybeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get maybe internal server error response
func (o *GetMaybeInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMaybeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
