// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/LGUG2Z/call-me/models"
)

// PostMaybeHandlerFunc turns a function with the right signature into a post maybe handler
type PostMaybeHandlerFunc func(PostMaybeParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostMaybeHandlerFunc) Handle(params PostMaybeParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostMaybeHandler interface for that can handle valid post maybe params
type PostMaybeHandler interface {
	Handle(PostMaybeParams, *models.Principal) middleware.Responder
}

// NewPostMaybe creates a new http.Handler for the post maybe operation
func NewPostMaybe(ctx *middleware.Context, handler PostMaybeHandler) *PostMaybe {
	return &PostMaybe{Context: ctx, Handler: handler}
}

/*PostMaybe swagger:route POST /maybe postMaybe

Take an open slot

*/
type PostMaybe struct {
	Context *middleware.Context
	Handler PostMaybeHandler
}

func (o *PostMaybe) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostMaybeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
