// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "call-me",
    "version": "0.1.0"
  },
  "paths": {
    "/maybe": {
      "get": {
        "security": [
          {
            "APIKeyHeader": []
          }
        ],
        "summary": "Check if there is an open slot",
        "operationId": "GetMaybe",
        "parameters": [
          {
            "$ref": "#/parameters/Environment"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      },
      "post": {
        "security": [
          {
            "APIKeyHeader": []
          }
        ],
        "summary": "Take an open slot",
        "operationId": "PostMaybe",
        "parameters": [
          {
            "$ref": "#/parameters/Environment"
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      },
      "delete": {
        "security": [
          {
            "APIKeyHeader": []
          }
        ],
        "summary": "Free a token slot",
        "operationId": "DeleteMaybe",
        "parameters": [
          {
            "$ref": "#/parameters/Environment"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      }
    }
  },
  "definitions": {
    "principal": {
      "type": "string"
    }
  },
  "parameters": {
    "Environment": {
      "type": "string",
      "description": "Environment name",
      "name": "environment",
      "in": "query",
      "required": true
    }
  },
  "responses": {
    "InternalServerError": {
      "description": "Internal Server Error",
      "schema": {
        "type": "string"
      }
    }
  },
  "securityDefinitions": {
    "APIKeyHeader": {
      "type": "apiKey",
      "name": "X-API-KEY",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "call-me",
    "version": "0.1.0"
  },
  "paths": {
    "/maybe": {
      "get": {
        "security": [
          {
            "APIKeyHeader": []
          }
        ],
        "summary": "Check if there is an open slot",
        "operationId": "GetMaybe",
        "parameters": [
          {
            "type": "string",
            "description": "Environment name",
            "name": "environment",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "APIKeyHeader": []
          }
        ],
        "summary": "Take an open slot",
        "operationId": "PostMaybe",
        "parameters": [
          {
            "type": "string",
            "description": "Environment name",
            "name": "environment",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "APIKeyHeader": []
          }
        ],
        "summary": "Free a token slot",
        "operationId": "DeleteMaybe",
        "parameters": [
          {
            "type": "string",
            "description": "Environment name",
            "name": "environment",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "principal": {
      "type": "string"
    }
  },
  "parameters": {
    "Environment": {
      "type": "string",
      "description": "Environment name",
      "name": "environment",
      "in": "query",
      "required": true
    }
  },
  "responses": {
    "InternalServerError": {
      "description": "Internal Server Error",
      "schema": {
        "type": "string"
      }
    }
  },
  "securityDefinitions": {
    "APIKeyHeader": {
      "type": "apiKey",
      "name": "X-API-KEY",
      "in": "header"
    }
  }
}`))
}
