// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteMaybeParams creates a new DeleteMaybeParams object
// with the default values initialized.
func NewDeleteMaybeParams() *DeleteMaybeParams {
	var ()
	return &DeleteMaybeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteMaybeParamsWithTimeout creates a new DeleteMaybeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteMaybeParamsWithTimeout(timeout time.Duration) *DeleteMaybeParams {
	var ()
	return &DeleteMaybeParams{

		timeout: timeout,
	}
}

// NewDeleteMaybeParamsWithContext creates a new DeleteMaybeParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteMaybeParamsWithContext(ctx context.Context) *DeleteMaybeParams {
	var ()
	return &DeleteMaybeParams{

		Context: ctx,
	}
}

// NewDeleteMaybeParamsWithHTTPClient creates a new DeleteMaybeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteMaybeParamsWithHTTPClient(client *http.Client) *DeleteMaybeParams {
	var ()
	return &DeleteMaybeParams{
		HTTPClient: client,
	}
}

/*DeleteMaybeParams contains all the parameters to send to the API endpoint
for the delete maybe operation typically these are written to a http.Request
*/
type DeleteMaybeParams struct {

	/*Environment
	  Environment name

	*/
	Environment string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete maybe params
func (o *DeleteMaybeParams) WithTimeout(timeout time.Duration) *DeleteMaybeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete maybe params
func (o *DeleteMaybeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete maybe params
func (o *DeleteMaybeParams) WithContext(ctx context.Context) *DeleteMaybeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete maybe params
func (o *DeleteMaybeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete maybe params
func (o *DeleteMaybeParams) WithHTTPClient(client *http.Client) *DeleteMaybeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete maybe params
func (o *DeleteMaybeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironment adds the environment to the delete maybe params
func (o *DeleteMaybeParams) WithEnvironment(environment string) *DeleteMaybeParams {
	o.SetEnvironment(environment)
	return o
}

// SetEnvironment adds the environment to the delete maybe params
func (o *DeleteMaybeParams) SetEnvironment(environment string) {
	o.Environment = environment
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMaybeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param environment
	qrEnvironment := o.Environment
	qEnvironment := qrEnvironment
	if qEnvironment != "" {
		if err := r.SetQueryParam("environment", qEnvironment); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
