// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetMaybeReader is a Reader for the GetMaybe structure.
type GetMaybeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMaybeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMaybeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewGetMaybeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetMaybeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetMaybeOK creates a GetMaybeOK with default headers values
func NewGetMaybeOK() *GetMaybeOK {
	return &GetMaybeOK{}
}

/*GetMaybeOK handles this case with default header values.

OK
*/
type GetMaybeOK struct {
}

func (o *GetMaybeOK) Error() string {
	return fmt.Sprintf("[GET /maybe][%d] getMaybeOK ", 200)
}

func (o *GetMaybeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetMaybeForbidden creates a GetMaybeForbidden with default headers values
func NewGetMaybeForbidden() *GetMaybeForbidden {
	return &GetMaybeForbidden{}
}

/*GetMaybeForbidden handles this case with default header values.

Forbidden
*/
type GetMaybeForbidden struct {
}

func (o *GetMaybeForbidden) Error() string {
	return fmt.Sprintf("[GET /maybe][%d] getMaybeForbidden ", 403)
}

func (o *GetMaybeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetMaybeInternalServerError creates a GetMaybeInternalServerError with default headers values
func NewGetMaybeInternalServerError() *GetMaybeInternalServerError {
	return &GetMaybeInternalServerError{}
}

/*GetMaybeInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetMaybeInternalServerError struct {
	Payload string
}

func (o *GetMaybeInternalServerError) Error() string {
	return fmt.Sprintf("[GET /maybe][%d] getMaybeInternalServerError  %+v", 500, o.Payload)
}

func (o *GetMaybeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
