// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMaybeParams creates a new GetMaybeParams object
// with the default values initialized.
func NewGetMaybeParams() *GetMaybeParams {
	var ()
	return &GetMaybeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMaybeParamsWithTimeout creates a new GetMaybeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMaybeParamsWithTimeout(timeout time.Duration) *GetMaybeParams {
	var ()
	return &GetMaybeParams{

		timeout: timeout,
	}
}

// NewGetMaybeParamsWithContext creates a new GetMaybeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMaybeParamsWithContext(ctx context.Context) *GetMaybeParams {
	var ()
	return &GetMaybeParams{

		Context: ctx,
	}
}

// NewGetMaybeParamsWithHTTPClient creates a new GetMaybeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMaybeParamsWithHTTPClient(client *http.Client) *GetMaybeParams {
	var ()
	return &GetMaybeParams{
		HTTPClient: client,
	}
}

/*GetMaybeParams contains all the parameters to send to the API endpoint
for the get maybe operation typically these are written to a http.Request
*/
type GetMaybeParams struct {

	/*Environment
	  Environment name

	*/
	Environment string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get maybe params
func (o *GetMaybeParams) WithTimeout(timeout time.Duration) *GetMaybeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get maybe params
func (o *GetMaybeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get maybe params
func (o *GetMaybeParams) WithContext(ctx context.Context) *GetMaybeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get maybe params
func (o *GetMaybeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get maybe params
func (o *GetMaybeParams) WithHTTPClient(client *http.Client) *GetMaybeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get maybe params
func (o *GetMaybeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironment adds the environment to the get maybe params
func (o *GetMaybeParams) WithEnvironment(environment string) *GetMaybeParams {
	o.SetEnvironment(environment)
	return o
}

// SetEnvironment adds the environment to the get maybe params
func (o *GetMaybeParams) SetEnvironment(environment string) {
	o.Environment = environment
}

// WriteToRequest writes these params to a swagger request
func (o *GetMaybeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param environment
	qrEnvironment := o.Environment
	qEnvironment := qrEnvironment
	if qEnvironment != "" {
		if err := r.SetQueryParam("environment", qEnvironment); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
