// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostMaybeReader is a Reader for the PostMaybe structure.
type PostMaybeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMaybeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostMaybeCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewPostMaybeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPostMaybeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostMaybeCreated creates a PostMaybeCreated with default headers values
func NewPostMaybeCreated() *PostMaybeCreated {
	return &PostMaybeCreated{}
}

/*PostMaybeCreated handles this case with default header values.

Created
*/
type PostMaybeCreated struct {
}

func (o *PostMaybeCreated) Error() string {
	return fmt.Sprintf("[POST /maybe][%d] postMaybeCreated ", 201)
}

func (o *PostMaybeCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostMaybeForbidden creates a PostMaybeForbidden with default headers values
func NewPostMaybeForbidden() *PostMaybeForbidden {
	return &PostMaybeForbidden{}
}

/*PostMaybeForbidden handles this case with default header values.

Forbidden
*/
type PostMaybeForbidden struct {
}

func (o *PostMaybeForbidden) Error() string {
	return fmt.Sprintf("[POST /maybe][%d] postMaybeForbidden ", 403)
}

func (o *PostMaybeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostMaybeInternalServerError creates a PostMaybeInternalServerError with default headers values
func NewPostMaybeInternalServerError() *PostMaybeInternalServerError {
	return &PostMaybeInternalServerError{}
}

/*PostMaybeInternalServerError handles this case with default header values.

Internal Server Error
*/
type PostMaybeInternalServerError struct {
	Payload string
}

func (o *PostMaybeInternalServerError) Error() string {
	return fmt.Sprintf("[POST /maybe][%d] postMaybeInternalServerError  %+v", 500, o.Payload)
}

func (o *PostMaybeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
